include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    todo: ignore
    include_file_not_found: ignore
  exclude:
    - vendor/**
    - '**/*.g.dart'
linter:
  rules:
    ## The following rules are excluded only to keep compatibility with our previous lint set (pedantic).
    ## There's room to discuss them individually and raise PRs adjusting our codebase.
    avoid_print: false
    prefer_function_declarations_over_variables: false
    constant_identifier_names: false
    prefer_const_declarations: false
    prefer_typing_uninitialized_variables: false
    prefer_is_not_operator: false
    unnecessary_string_interpolations: false
    sized_box_for_whitespace: false
    prefer_const_literals_to_create_immutables: false
    use_key_in_widget_constructors: false
    avoid_unnecessary_containers: false
    unnecessary_string_escapes: false
    file_names: false
    non_constant_identifier_names: false
    void_checks: false
    avoid_function_literals_in_foreach_calls: false
    empty_statements: false
    no_logic_in_create_state: false
    implementation_imports: false
    overridden_fields: false